name: CI
on:
  push:
  pull_request:
jobs:
  api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r api/requirements.txt
      - name: Run tests
        working-directory: api
        run: pytest -q

